code --install extension ardenivanov.svelte-intellisense
code --install extension bceskavich.theme-dracula-at-night
code --install extension dracula-theme.theme-dracula
code --install extension fivethree.vscode-svelte-snippets
code --install extension formulahendry.code-runner
code --install extension JamesBirtles.svelte-vscode
code --install extension ms-python.python
code --install extension ms-vscode-remote.remote-wsl
code --install extension npxms.hide-gitignored
code --install extension ritwickdey.LiveServer
code --install extension rust-lang.rust
code --install extension slevesque.vscode-autohotkey
code --install extension VisualStudioExptTeam.vscodeintellicode
code --install extension yzhang.markdown-all-in-one
