[character]
success_symbol = "=>(bold green)"

[cmd_duration]
disabled = true
show_notifications = true

[kubernetes]
disabled = false
style = 'blue bold'

[status]
disabled = true

[time]
disabled = false
